name: Bun CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Bun.js ${{ matrix.bun-version }}

        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: npm install, build
        run: |
          bun install
          rm -rf dist
        env:
          CI: true

      - name: Run linter
        run: bun lint
      - name: Run tests
        run: bun tests ci
