name: Node CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build
        run: |
          npm ci
          rm -rf dist
        env:
          CI: true

      - name: Run linter
        run: npx ng lint
      - name: Run tests
        run: "echo 'no tests available at the moment'"
